SGUevents/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users.views import telegram_webhook

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('support/', include('support.urls', namespace='support')),
    path('events_available/', include('events_available.urls', namespace='events_available')),
    path('events_calendar/', include('events_calendar.urls', namespace='events_calendar')),
    path('events_cultural/', include('events_cultural.urls', namespace='events_cultural')),
    path('application_for_admin_rights/', include('application_for_admin_rights.urls', namespace='application_for_admin_rights')),
    path('personal/', include('personal.urls', namespace='personal')),
    path('select2/', include('django_select2.urls')),
    path('bookmarks/', include('bookmarks.urls', namespace='bookmarks')),
    path('webhook/', telegram_webhook, name='telegram_webhook'),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events_available/urls.py
from django.urls import path, include
from events_available import views

app_name = 'events_available'

urlpatterns = [
	path('search/online/', views.online, name='search_online'),
	path('search/offline/', views.offline, name='search_offline'),

	path('online/<int:page>/', views.online, name='online'),
	path('online/', views.online, name='online'),
	path('online/<slug:event_slug>/', views.online_card, name='online_card'),
	
	path('offline/<int:page>/', views.online, name='offline'),
	path('offline/', views.offline, name='offline'),
	path('offline/<slug:event_slug>/', views.offline_card, name='offline_card'),
	
	path('submit_review/<int:event_id>/', views.submit_review, name='submit_review'),
	path('autocomplete/places/', views.autocomplete_places, name='autocomplete_places'),
]

events_cultural/urls.py
from django.urls import path, include
from events_cultural import views

app_name = 'events_cultural'

urlpatterns = [
	path('attractions/search/', views.attractions, name='search_attractions'),
	path('events_for_visiting/search/', views.events_for_visiting, name='search_events_for_visiting'),


	path('attractions/<int:page>/', views.attractions, name='attractions'),
	path('attractions/', views.attractions, name='attractions'),
	path('attractions/<slug:event_slug>/', views.attractions_card, name='attractions_card'),

	# path('events_registered/', views.events_registered, name='events_registered'),
	# path('events_registered/<int:event_id>', views.events_registered_, name='events_registered_card'),
	# path('events_registered/event/<slug:event_slug>/', views.events_registered, name='events_registered_card'),

	path('events_for_visiting/<int:page>/', views.events_for_visiting, name='events_for_visiting'),
	path('events_for_visiting/', views.events_for_visiting, name='events_for_visiting'),
	path('events_for_visiting/<slug:event_slug>/', views.for_visiting_card, name='events_for_visiting_card'),

	path('submit_review/<int:event_id>/', views.submit_review, name='submit_review'),
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
	path('search/all/', views.index, name='search_all')
]

events_available/views.py
from django.http import JsonResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render
from bookmarks.models import Favorite, Registered
from events_available.models import Events_offline, Events_online
from django.core.paginator import Paginator
from events_available.utils import q_search_offline, q_search_online, q_search_name_offline
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.contenttypes.models import ContentType
from bookmarks.models import Review
from users.models import Department, User
from django.db.models import Q
from django.db.models import CharField, Value
from django.db.models.functions import Concat



@login_required
def online(request):
    page = request.GET.get('page', 1)
    f_date = request.GET.get('f_date', None)
    f_speakers = request.GET.getlist('f_speakers', None)
    f_tags = request.GET.getlist('f_tags', None)
    order_by = request.GET.get('order_by', None)
    date_start = request.GET.get('date_start', None)
    date_end = request.GET.get('date_end', None)
    time_to_start = request.GET.get('time_to_start', None)
    time_to_end = request.GET.get('time_to_end', None)
    query = request.GET.get('q', None)
    user = request.user

    all_info = Events_online.objects.all()
    # Получаем всех спикеров через отношение ManyToMany
    speakers_set = set()
    for event in all_info:
        for speaker in event.speakers.all():
            speakers_set.add(speaker.get_full_name())

    speakers = list(speakers_set)

    # Получаем всех админов через отношение ManyToMany
    events_admin_set = set()
    for event in all_info:
        for admin in event.events_admin.all():
            events_admin_set.add(admin.get_full_name())

    events_admin = list(events_admin_set)
    
    if not query:
        events_available = Events_online.objects.order_by('date')
    else:
        events_available = q_search_online(query)

    #Фильтрация по скрытым мероприятиям
    if user.is_superuser or user.department.department_name in ['Administration', 'Superuser']:
        pass 
    else:
        if user.department:
            events_available = events_available.filter(Q(secret__isnull=True) | Q(secret=user.department)).distinct()
        else:
            events_available = events_available.filter(secret__isnull=True).distinct()

    if f_date:
        events_available = events_available.filter(date__month=1)

    if f_speakers:
        events_available = events_available.filter(speakers__in=f_speakers)
    # if f_speakers:
    #     speakers_query = Q()
    #     for speaker in f_speakers:
    #         speakers_query |= Q(speakers__icontains=speaker)
    #     events_available = events_available.filter(speakers_query)

    tags = [event.tags for event in all_info]

    if f_tags:
        tags_query = Q()
        for tag in f_tags:
            tags_query |= Q(tags__icontains=tag)
        events_available = events_available.filter(tags_query)

    if order_by and order_by != "default":
        events_available = events_available.order_by(order_by)

    if date_start:
        date_start_formatted = datetime.strptime(date_start, '%Y-%m-%d').date()
        events_available = events_available.filter(date__gt=date_start_formatted)

    if date_end:
        date_end_formatted = datetime.strptime(date_end, '%Y-%m-%d').date()
        events_available = events_available.filter(date__lt=date_end_formatted)

    paginator = Paginator(events_available, 3)
    current_page = paginator.page(int(page))

    favorites = Favorite.objects.filter(user=request.user, online__in=current_page)
    favorites_dict = {favorite.online.id: favorite.id for favorite in favorites}

    registered = Registered.objects.filter(user=request.user, online__in=current_page)
    registered_dict = {reg.online.id: reg.id for reg in registered}

    reviews = {}
    for event in current_page:
        content_type = ContentType.objects.get_for_model(event)
        reviews[event.unique_id] = Review.objects.filter(content_type=content_type, object_id=event.id)

    context = {
        'name_page': 'Онлайн',
        'event_card_views': current_page,
        'speakers': speakers,
        'events_admin': events_admin,
        'tags': tags,
        'favorites': favorites_dict,
        'registered': registered_dict,
        'reviews': reviews,
    }

    return render(request, 'events_available/online_events.html', context=context)


@login_required
def online_card(request, event_slug=False, event_id=False):
    reviews = {}
    if event_id:
        event = Events_online.objects.get(id=event_id)
    else:
        event = Events_online.objects.get(slug=event_slug)

    events = Events_online.objects.all()
    
    favorites = Favorite.objects.filter(user=request.user, online__in=events)
    favorites_dict = {favorite.online.id: favorite.id for favorite in favorites}

    registered = Registered.objects.filter(user=request.user, online__in=events)
    registered_dict = {reg.online.id: reg.id for reg in registered}

    reviews = {}

    for event_rew in events:
        content_type = ContentType.objects.get_for_model(event)
        reviews[event_rew.unique_id] = Review.objects.filter(content_type=content_type, object_id=event.id)

    context = {
        'event': event,
        'reviews': reviews,
        'registered': registered_dict,
        'favorites': favorites_dict, 
    }
    return render(request, 'events_available/card.html', context=context)


@login_required
def offline(request):
    page = request.GET.get('page', 1)
    f_date = request.GET.getlist('f_date', None)
    f_speakers = request.GET.getlist('f_speakers', None)
    f_tags = request.GET.getlist('f_tags', None)
    f_place = request.GET.get('f_place', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)
    query_name = request.GET.get('qn', None)
    date_start = request.GET.get('date_start', None)
    date_end = request.GET.get('date_end', None)
    user = request.user

    all_info = Events_offline.objects.all()
    # Получаем всех спикеров
    speakers_set = set()
    for event in all_info:
        for speaker in event.speakers.all():
            speakers_set.add(speaker.get_full_name())

    speakers = list(speakers_set)

    for name in speakers:
        names_list = name.split()
        for i in range(0, len(names_list), 3):
            speakers_set.add(' '.join(names_list[i:i+3]))
    
    speakers = list(speakers_set)

    # Получаем всех админов через отношение ManyToMany
    events_admin_set = set()
    for event in all_info:
        for admin in event.events_admin.all():
            events_admin_set.add(admin.get_full_name())

    events_admin = list(events_admin_set)

    if not query_name:
        events_available = Events_offline.objects.order_by('time_start')
    else:
        events_available = q_search_name_offline(query_name)

    if not query:
        events_available = events_available.order_by('time_start')
    else:
        events_available = q_search_offline(query)

    #Фильтрация по скрытым мероприятиям
    if user.is_superuser or user.department.department_name in ['Administration', 'Superuser']:
        pass 
    else:
        if user.department:
            events_available = events_available.filter(Q(secret__isnull=True) | Q(secret=user.department)).distinct()
        else:
            events_available = events_available.filter(secret__isnull=True).distinct()

    if f_date:
        events_available = events_available.filter(date__month=1)

    if date_start:
        date_start_formatted = datetime.strptime(date_start, '%Y-%m-%d').date()
        events_available = events_available.filter(date__gte=date_start_formatted) 

    if date_end:
        date_end_formatted = datetime.strptime(date_end, '%Y-%m-%d').date()
        events_available = events_available.filter(date__lte=date_end_formatted)

    if f_place:
        events_available = events_available.annotate(
            full_place=Concat('town', Value(' '), 'street', Value(' '), 'house', Value(' '), 'cabinet', output_field=CharField())
        ).filter(full_place__icontains=f_place)


    if f_speakers:
        events_available = events_available.filter(speakers__in=f_speakers)
    # if f_speakers:
    #     speakers_query = Q()
    #     for speaker in f_speakers:
    #         speakers_query |= Q(speakers__icontains=speaker)
    #     events_available = events_available.filter(speakers_query)

    tags = [event.tags for event in all_info]

    if f_tags:
        tags_query = Q()
        for tag in f_tags:
            tags_query |= Q(tags__icontains=tag)
        events_available = events_available.filter(tags_query)

    if order_by and order_by != "default":
        events_available = events_available.order_by(order_by)

    

    paginator = Paginator(events_available, 3)
    current_page = paginator.page(int(page))

    favorites = Favorite.objects.filter(user=request.user, offline__in=current_page)
    favorites_dict = {favorite.offline.id: favorite.id for favorite in favorites}

    registered = Registered.objects.filter(user=request.user, offline__in=current_page)
    registered_dict = {reg.offline.id: reg.id for reg in registered}

    reviews = {}
    for event in current_page:
        content_type = ContentType.objects.get_for_model(event)
        reviews[event.unique_id] = Review.objects.filter(content_type=content_type, object_id=event.id)

    results = Events_offline.objects.annotate(
    full_address=Concat('town', Value(' '), 'street', Value(' '), 'house', Value(' '), 'cabinet', output_field=CharField())
    ).values_list('full_address', flat=True)
    results = sorted(set(results))
   

    context = {
        'name_page': 'Оффлайн',
        'event_card_views': current_page,
        'speakers': speakers,
        'events_admin': events_admin,
        'tags': tags,
        'favorites': favorites_dict,

events_available/templates/events_available/card.html
{% extends 'events/card.html' %} 
{% load static %} 
{% load events_available_tags %}

{% block heart %}

{% if event.category == "Оффлайн" %}
	{% if event.id in favorites %}
	<a href="#" class="btn remove-from-favorites" data-event-id="{{ favorites|get_item:event.id }}">
		<img class="mx-1 heart-icon" src="{% static 'general/icons/heart_red.png' %}" alt="Catalog Icon" width="32" height="32">
	</a>
	{% else %}
	<a href="#" class="btn add-to-cart" data-event-slug="{{ event.slug }}">
		<img class="mx-1 heart-icon" src="{% static 'general/icons/heart.svg' %}" alt="Catalog Icon" width="32" height="32">
	</a>
	{% endif %}
{% elif event.category == "Онлайн" %}
	{% if event.id in favorites %}
	<a href="#" class="btn remove-from-favorites" data-event-id="{{ favorites|get_item:event.id }}">
		<img class="mx-1 heart-icon" src="{% static 'general/icons/heart_red.png' %}" alt="Catalog Icon" width="32" height="32">
	</a>
	{% else %}
	<a href="#" class="btn add-to-cart" data-event-slug="{{ event.slug }}">
		<img class="mx-1 heart-icon" src="{% static 'general/icons/heart.svg' %}" alt="Catalog Icon" width="32" height="32">
	</a>
	{% endif %}
{% endif %}

{% endblock heart %}


{% block content %}
<!-- Контент на странице -->

{% if event.category == "Оффлайн" %}
	{% if event.id in registered %}
		<a href="#" class="btn btn-light btn-remove_app" data-event-id="{{ registered|get_item:event.id }}">
			Отмена регистрации
		</a>
	{% else %}
		<a href="#" class="btn btn-danger btn-sent_app" data-event-slug="{{ event.slug }}">
			Регистрация
		</a>
	{% endif %}

	<button class="btn btn-primary btn-comment" data-event-id="{{ event.id }}" data-model-type="offline">Оставить отзыв</button>


{% elif event.category == "Онлайн" %}
	{% if event.id in registered %}
		<a href="#" class="btn btn-light btn-remove_app" data-event-id="{{ registered|get_item:event.id }}">
			Отмена регистрации
		</a>
	{% else %}
		<a href="#" class="btn btn-danger btn-sent_app" data-event-slug="{{ event.slug }}">
			Регистрация
		</a>
	{% endif %}

		<button class="btn btn-primary btn-comment" data-event-id="{{ event.id }}" data-model-type="online">Оставить отзыв</button>
{% endif %}

{% endblock content %}

events_available/templates/events_available/offline_events.html
{% extends 'events/base.html' %}
{% load static %}
{% load events_available_tags %}
{% block title %} <title>Оффлайн мероприятия</title> {% endblock %}
{% block filters %}
<div class="row filter-events-row mt-2">
    <div class="col-lg-2">
        <div class="row">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Название 
                </button>
                <form action="{% if name_page == 'Онлайн' %}{% url "events_available:search_online" %}{% elif name_page == 'Оффлайн' %}{% url "events_available:search_offline" %}{% elif name_page == 'Доступные к посещению' %}{% url "events_cultural:search_events_for_visiting" %}{% elif name_page == 'Достопримечательности' %}{% url "events_cultural:search_attractions" %}{% elif name_page == 'Все мероприятия' %}{% url "main:search_all" %}{% endif %}" method="get" class="dropdown-menu bg-dark w-100" data-bs-theme="dark">
                    <div class="form-check text-white">
                        <input class="form-control me-3 " type="search" name="qn" placeholder="Search" aria-label="Search" >
                    </div>
                    <button class="btn btn-outline-success d-inline" type="submit">
                        Найти <img src="{% static "general/icons/search.svg" %}" alt="S">
                    </button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="row">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false"> 
                    Дата
                </button>
                <form action="#" method="get" class="dropdown-menu bg-dark ca" data-bs-theme="dark" style="">
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="checkbox" name="f_date" id="flexCheckDefault" value="on" 
                        {% if request.GET.f_offline == 'on' %}checked{% endif %}>
                        {% if request.GET.q %}
                            <input type="hidden" name="q" value="{{ request.GET.q }}"> 
                        {% endif %}
                        <label class="form-check-label" for="flexCheckDefault">Январь</label>
                    </div>
                    <div class="form-check text-white">
                        Дата начала  <br/>							
                        <label class="form-check-label" for="flexCheckDefault">
                            <input type="date" id="date_start" name="date_start" value="date_low">
                        </label>
                    </div>
                    <div class="form-check text-white">	
                        Дата окончания <br/>
                        <label class="form-check-label" for="flexCheckDefault">
                            <input type="date" id="date_end" name="date_end" value="date_last">
                        </label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                        {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                        <label class="form-check-label" for="flexRadioDefault1">По умолчанию</label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="-date" 
                        {% if request.GET.order_by == '-date' %}checked{% endif %}>
                        <label class="form-check-label" for="flexRadioDefault2">Сначала новые</label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="date" 
                        {% if request.GET.order_by == 'date' %}checked{% endif %}>
                        <label class="form-check-label" for="flexRadioDefault3">Сначала старые</label>
                    </div>
                    <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="row">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Время
                </button>
                <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                    <div class="form-check text-white">
                        Время начала  <br/>							
                        <label class="form-check-label" for="flexCheckDefault">
                            <input type="time" id="time_to_start" name="time_to_start" value="hh-mm-ss">
                        </label>
                    </div>
                    <div class="form-check text-white">
                        Время окончания  <br/>							
                        <label class="form-check-label" for="flexCheckDefault">
                            <input type="time" id="time_to_end" name="time_to_end" value="hh-mm-ss">
                        </label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                        <label class="form-check-label" for="flexRadioDefault1">По умолчанию</label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="time_start" {% if request.GET.order_by == 'time_start' %}checked{% endif %}>
                        <label class="form-check-label" for="flexRadioDefault2">Раньше</label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-time_start" {% if request.GET.order_by == '-time_start' %}checked{% endif %}>
                        <label class="form-check-label" for="flexRadioDefault3">Позже</label>
                    </div>
                    <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="row">
            <div class="dropdown">
                <form action="{% url 'events_available:offline' %}" method="get">
                    <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Место проведения
                    </button>
                    <div class="dropdown-menu bg-dark p-3" data-bs-theme="dark" style="width: 300px;">
                        <input type="text" id="address-input" name="f_place" placeholder="Введите адрес" class="form-control w-100" list="citylist">
                        <datalist id="citylist">
                            {% for result in results %}
                                <option value="{{ result }}">
                            {% endfor %}
                        </datalist>
                        <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    <div class="col-lg-2">
        <div class="row">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Спикеры
                </button>
                <form action="#" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark" style="max-height: 200px; overflow-y: auto;">
                    <div class="form-check text-white mx-3">
                        {% for speaker in speakers %}
                            <input class="form-check-input" type="checkbox" name="f_speakers" id="flexCheckDefault{{ forloop.counter }}" value="{{ speaker }}" 
                            {% if request.GET.f_offline == speaker %}checked{% endif %}>
                            {% if request.GET.q %}
                                <input type="hidden" name="q" value="{{ request.GET.q }}"> 
                            {% endif %}
                            <label class="form-check-label" for="flexCheckDefault{{ forloop.counter }}">
                                {{ speaker }}
                            </label>
                            <br>
                        {% endfor %}
                    </div>

                        {% comment %} Для объединения фильтров {% endcomment %}
                    {% for key, value in request.GET.items %}
                        {% if key != 'f_speakers' %}
                            <input type="hidden" name="{{ key }}" value="{{ value }}">
                        {% endif %}
                    {% endfor %}

                    <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-2">
        <div class="row">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Теги
                </button>
                <form action="#" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark" style="max-height: 200px; overflow-y: auto;">
                    <div class="form-check text-white mx-3">
                        {% for tag in tags %}
                            <input class="form-check-input" type="checkbox" name="f_tags" id="flexCheckDefault{{ forloop.counter }}" value="{{ tag }}" 
                            {% if request.GET.f_offline == tag %}checked{% endif %}>
                            {% if request.GET.q %}
                                <input type="hidden" name="q" value="{{ request.GET.q }}"> 
                            {% endif %}
                            <label class="form-check-label" for="flexCheckDefault{{ forloop.counter }}">
                                {{ tag }}
                            </label>
                            <br>
                        {% endfor %}
                    </div>

                        {% comment %} Для объединения фильтров {% endcomment %}
                    {% for key, value in request.GET.items %}
                        {% if key != 'f_speakers' %}
                            <input type="hidden" name="{{ key }}" value="{{ value }}">
                        {% endif %}
                    {% endfor %}

                    <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-2">
        <form action="{% url 'events_available:offline' %}" method="get">
        <button class="btn btn-primary" type="submit">Сбросить</button>
    </form>
    </div>
</div>
{% endblock filters %}

{% block content %}
<!-- Контент на странице -->
{% if events.id in registered %}

<a href="#" class="btn btn-light btn-remove_app" data-event-id="{{ registered|get_item:events.id }}">
    Отмена регистрации
</a>
{% else %}
<a href="#" class="btn btn-danger btn-sent_app" data-event-slug="{{ events.slug }}">
    Регистрация
</a>
{% endif %}

<button class="btn btn-primary btn-comment" data-event-id="{{ events.id }}" data-model-type="offline">Оставить отзыв</button>

{% endblock content %}