SGUevents/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users.views import telegram_webhook

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('support/', include('support.urls', namespace='support')),
    path('events_available/', include('events_available.urls', namespace='events_available')),
    path('events_calendar/', include('events_calendar.urls', namespace='events_calendar')),
    path('events_cultural/', include('events_cultural.urls', namespace='events_cultural')),
    path('application_for_admin_rights/', include('application_for_admin_rights.urls', namespace='application_for_admin_rights')),
    path('personal/', include('personal.urls', namespace='personal')),
    path('select2/', include('django_select2.urls')),
    path('bookmarks/', include('bookmarks.urls', namespace='bookmarks')),
    path('webhook/', telegram_webhook, name='telegram_webhook'),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/urls.py
from django.urls import path
from bookmarks import views
from .views import send_message_to_participants, get_event_choices

app_name = 'bookmarks'

urlpatterns = [
    path('events_add/<slug:event_slug>/', views.events_add, name='events_add'),
    path('events_remove/<int:event_id>/', views.events_remove, name='events_remove'),
    path('favorites/', views.favorites, name='favorites'),

    path('favorites/', views.favorites, name='favorites'),
    path('favorites/<slug:event_slug>/', views.favorites, name='toggle_favorite'),

	path('events_attended/', views.events_attended, name='events_attended'),
	path('events_attended/<slug:event_slug>/', views.events_attended, name='events_attended'),

    path('events_registered/', views.events_registered, name='events_registered'),
    path('events_registered/<slug:event_slug>/', views.events_registered, name='events_registered'),
    path('registered_remove/<int:event_id>/', views.registered_remove, name='registered_remove'),
    path('registered/', views.registered, name='registered'),
    path('registered/<slug:event_slug>/', views.registered, name='registered'),
    path('send_message/', send_message_to_participants, name='send_message_to_participants'),
    path('get-event-choices/', get_event_choices, name='get_event_choices'),
    path('submit_review/<int:event_id>/', views.submit_review, name='submit_review'),
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
	path('search/all/', views.index, name='search_all')
]

bookmarks/forms.py
from django import forms
from events_available.models import Events_online, Events_offline
from events_cultural.models import Attractions, Events_for_visiting


class SendMessageForm(forms.Form):
    event_choices = [
        ('online', 'Онлайн мероприятия'),
        ('offline', 'Оффлайн мероприятия'),
        ('attractions', 'Достопримечательности'),
        ('for_visiting', 'Доступные для посещения'),
    ]

    event_type = forms.ChoiceField(choices=event_choices, label='Тип мероприятия')
    event = forms.ModelChoiceField(queryset=Events_online.objects.none(), label='Мероприятие', required=False)
    message = forms.CharField(widget=forms.Textarea, label='Сообщение')

    def __init__(self, *args, **kwargs):
        event_type = kwargs.pop('event_type', None)  # Извлекаем event_type из kwargs
        super(SendMessageForm, self).__init__(*args, **kwargs)

        if event_type:
            # Устанавливаем queryset в зависимости от выбранного типа мероприятия
            self.set_event_queryset(event_type)
        else:
            # По умолчанию оставляем queryset пустым
            self.fields['event'].queryset = Events_online.objects.none()

    def set_event_queryset(self, event_type):
        if event_type == 'online':
            self.fields['event'].queryset = Events_online.objects.all()
        elif event_type == 'offline':
            self.fields['event'].queryset = Events_offline.objects.all()
        elif event_type == 'attractions':
            self.fields['event'].queryset = Attractions.objects.all()
        elif event_type == 'for_visiting':
            self.fields['event'].queryset = Events_for_visiting.objects.all()

bookmarks/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from bookmarks.models import Favorite, Registered, Review
from events_available.models import Events_online, Events_offline
from events_cultural.models import Attractions, Events_for_visiting
from users.telegram_utils import send_message_to_user
from events_cultural.views import submit_review
from django.views.decorators.csrf import csrf_exempt
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from bookmarks.forms import SendMessageForm
from users.telegram_utils import send_notification_with_toggle
from bookmarks.models import Registered

@login_required
def events_add(request, event_slug):
    event = None
    event_type = None
    try:
        event = Events_online.objects.get(slug=event_slug)
        event_type = 'online'
    except Events_online.DoesNotExist:
        try:
            event = Events_offline.objects.get(slug=event_slug)
            event_type = 'offline'
        except Events_offline.DoesNotExist:
            try:
                event = Attractions.objects.get(slug=event_slug)
                event_type = 'attractions'
            except Attractions.DoesNotExist:
                try:
                    event = Events_for_visiting.objects.get(slug=event_slug)
                    event_type = 'for_visiting'
                except Events_for_visiting.DoesNotExist:
                    pass

    if event and request.user.is_authenticated:
        favorite, created = None, False
        if event_type == 'online':
            favorite, created = Favorite.objects.get_or_create(user=request.user, online=event)
        elif event_type == 'offline':
            favorite, created = Favorite.objects.get_or_create(user=request.user, offline=event)
        elif event_type == 'attractions':
            favorite, created = Favorite.objects.get_or_create(user=request.user, attractions=event)
        elif event_type == 'for_visiting':
            favorite, created = Favorite.objects.get_or_create(user=request.user, for_visiting=event)

        if not created:
            favorite.delete()
            added = False
        else:
            added = True

        return JsonResponse({'added': added, 'event_id': favorite.id})

    return JsonResponse({'error': 'Event not found or user not authenticated'}, status=400)

@login_required
def events_remove(request, event_id):
    if request.method == 'POST':
        favorite = get_object_or_404(Favorite, id=event_id, user=request.user)
        favorite.delete()
        return JsonResponse({'removed': True})
    return JsonResponse({'removed': False, 'error': 'Invalid request method'}, status=400)

@login_required
def favorites(request):
    favorites = Favorite.objects.filter(user=request.user).order_by('-created_timestamp')

    events = []
    for fav in favorites:
        if fav.online:
            events.append(fav.online)
        elif fav.offline:
            events.append(fav.offline)
        elif fav.attractions:
            events.append(fav.attractions)
        elif fav.for_visiting:
            events.append(fav.for_visiting)

    reviews = {}
    for event in events:
        content_type = ContentType.objects.get_for_model(event)
        reviews[event.unique_id] = Review.objects.filter(content_type=content_type, object_id=event.id)

    registered_dict = {
        'online': {},
        'offline': {},
        'attractions': {},
        'for_visiting': {}
    }

    # Получаем все зарегистрированные мероприятия и распределяем их по типам
    for event in events:
        if isinstance(event, Events_online):
            reg_event = Registered.objects.filter(user=request.user, online=event).first()
            if reg_event:
                registered_dict['online'][event.id] = reg_event.id
        elif isinstance(event, Events_offline):
            reg_event = Registered.objects.filter(user=request.user, offline=event).first()
            if reg_event:
                registered_dict['offline'][event.id] = reg_event.id
        elif isinstance(event, Attractions):
            reg_event = Registered.objects.filter(user=request.user, attractions=event).first()
            if reg_event:
                registered_dict['attractions'][event.id] = reg_event.id
        elif isinstance(event, Events_for_visiting):
            reg_event = Registered.objects.filter(user=request.user, for_visiting=event).first()
            if reg_event:
                registered_dict['for_visiting'][event.id] = reg_event.id

    context = {
        'events': events,
        'reviews': reviews,
        'favorites': favorites,
        'registered': registered_dict,
    }
    return render(request, 'bookmarks/favorites.html', context)

def events_attended(request):
    pass
    return render(request, "bookmarks/events_attended.html")

@login_required
def events_registered(request, event_slug):
    event = None
    event_type = None
    favorites = Favorite.objects.filter(user=request.user)



    try:
        event = Events_online.objects.get(slug=event_slug)
        event_type = 'online'
    except Events_online.DoesNotExist:
        try:
            event = Events_offline.objects.get(slug=event_slug)
            event_type = 'offline'
        except Events_offline.DoesNotExist:
            try:
                event = Attractions.objects.get(slug=event_slug)
                event_type = 'attractions'
            except Attractions.DoesNotExist:
                try:
                    event = Events_for_visiting.objects.get(slug=event_slug)
                    event_type = 'for_visiting'
                except Events_for_visiting.DoesNotExist:
                    pass

    if event and request.user.is_authenticated:
        registered, created = None, False
        if event_type == 'online':
            registered, created = Registered.objects.get_or_create(user=request.user, online=event)
        elif event_type == 'offline':
            registered, created = Registered.objects.get_or_create(user=request.user, offline=event)
        elif event_type == 'attractions':
            registered, created = Registered.objects.get_or_create(user=request.user, attractions=event)
        elif event_type == 'for_visiting':
            registered, created = Registered.objects.get_or_create(user=request.user, for_visiting=event)

        if created:
            return JsonResponse({'added': True, 'event_id': registered.id, 'event_slug': event_slug})
        else:
            return JsonResponse({'added': False, 'error': 'Already registered'}, status=400)

    return JsonResponse({'error': 'Event not found or user not authenticated'}, status=400)

@login_required
def registered_remove(request, event_id):
    if request.method == 'POST':
        event = get_object_or_404(Registered, id=event_id, user=request.user)
        event_name = (
            event.for_visiting.name if event.for_visiting else (
                event.online.name if event.online else (
                    event.offline.name if event.offline else (
                        event.attractions.name if event.attractions else None
                    )
                )
            )
        )
        event.delete()
        telegram_id = request.user.telegram_id
        if telegram_id:
            message = f"\U0000274C Вы успешно отменили регистрацию на мероприятие: {event_name}"
            send_message_to_user(telegram_id, message)
        return JsonResponse({'removed': True, 'event_name': event_name})
    return JsonResponse({'removed': False, 'error': 'Invalid request method'}, status=400)

@login_required
def registered(request):
    registered = Registered.objects.filter(user=request.user)
    reviews = {}
    events = []

    online_ids = []
    offline_ids = []
    attractions_ids = []
    for_visiting_ids = []

    for reg in registered:
        if reg.online:
            events.append(reg.online)
            online_ids.append(reg.online.id)
        elif reg.offline:
            events.append(reg.offline)
            offline_ids.append(reg.offline.id)
        elif reg.attractions:
            events.append(reg.attractions)
            attractions_ids.append(reg.attractions.id)
        elif reg.for_visiting:
            events.append(reg.for_visiting)
            for_visiting_ids.append(reg.for_visiting.id)

    for event in events:
        content_type = ContentType.objects.get_for_model(event)
        reviews[event.unique_id] = Review.objects.filter(content_type=content_type, object_id=event.id)

    favorites_online = Favorite.objects.filter(user=request.user, online_id__in=online_ids).values_list('online_id', 'id')
    favorites_offline = Favorite.objects.filter(user=request.user, offline_id__in=offline_ids).values_list('offline_id', 'id')
    favorites_attractions = Favorite.objects.filter(user=request.user, attractions_id__in=attractions_ids).values_list('attractions_id', 'id')
    favorites_for_visiting = Favorite.objects.filter(user=request.user, for_visiting_id__in=for_visiting_ids).values_list('for_visiting_id', 'id')

    favorites_dict = {
        'online': {item[0]: item[1] for item in favorites_online},
        'offline': {item[0]: item[1] for item in favorites_offline},
        'attractions': {item[0]: item[1] for item in favorites_attractions},
        'for_visiting': {item[0]: item[1] for item in favorites_for_visiting},
    }

    context = {
        'registered': registered,
        'reviews': reviews,
        'favorites': favorites_dict,
    }
    return render(request, 'bookmarks/registered.html', context)


@staff_member_required
def get_event_choices(request):
    event_type = request.GET.get('event_type')
    events = []

    if event_type == 'online':
        events = Events_online.objects.all()
    elif event_type == 'offline':

bookmarks/templates/bookmarks/events_attended.html
{% extends 'events/base.html' %} {% load static %} {% block title %} Главная
страница {% endblock %} {% block content %}
<!-- Контент на странице -->
 <p>Посещенные мероприятия</p>
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-1"></div>

		<div class="col-lg-10">
			<div class="row filter-events-row mt-2">
				<div class="col-lg-2 mx-1">
					<div class="row">
						<button type="button" class="btn btn-outline-dark">Дата</button>
					</div>
				</div>
				<div class="col-lg-2 mx-1">
					<div class="row">
						<button type="button" class="btn btn-outline-dark">Тема</button>
					</div>
				</div>
				<div class="col-lg-2 mx-1">
					<div class="row">
						<button type="button" class="btn btn-outline-dark">
							Место проведения
						</button>
					</div>
				</div>
				<div class="col-lg-2 mx-1">
					<div class="row">
						<button type="button" class="btn btn-outline-dark">Спикеры</button>
					</div>
				</div>
				<div class="col-lg-2 mx-1">
					<div class="row">
						<button type="button" class="btn btn-outline-dark">Теги</button>
					</div>
				</div>
				<div class="col-lg-2 mx-1">
					<div class="row"></div>
				</div>
			</div>

			<div class="row mt-3 mb-3 name-for-events">
				<div class="col-lg-12">
					<h2> {{ name_page }} </h2>
				</div>
			</div>

			<div class="row mt-2 event_cards">
				<div class="col-lg-12">
					<div class="card mb-3">
						<div class="row g-0">
							<div class="col-md-4">
								<img src="{% static "general/images/img.png" %}"
								class="img-fluid rounded-start" alt="...">
							</div>
							<div class="col-md-8">
								<div class="card-body">
									<h5 class="card-title">{{ 1_event_attended_title }}</h5>
									<h6 class="card-date"> 
										<split class="card-day"><b>01.03.2024</b></split> 
										<split class="card-time">14:00 - 18:00</split> </h6> 
									<p class="card-text">{{ 1_event_attended_info }}</p>
									<p class="card-text">
										<small class="text-muted">Тег</small>
									</p>
									<p class="card-text">
										<button type="button" class="btn btn-danger btn-registration">Регистрация</button>
						
										<button type="button" class="btn btn-light btn-canel-registration">Отмена регистрации</button>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="row mt-2 event_cards">
				<div class="col-lg-12">
					<div class="card mb-3">
						<div class="row g-0">
							<div class="col-md-4">
								<img src="{% static "general/images/img.png" %}"
								class="img-fluid rounded-start" alt="...">
							</div>
							<div class="col-md-8">
								<div class="card-body">
									<h5 class="card-title">{{ 2_event_attended_title }}</h5>
									<h6 class="card-date"> 
										<split class="card-day"><b>01.03.2024</b></split> 
										<split class="card-time">14:00 - 18:00</split> </h6> 
									<p class="card-text">{{ 2_event_attended_info }}</p>
									<p class="card-text">
										<small class="text-muted">Тег</small>
									</p>
									<p class="card-text">
										<button type="button" class="btn btn-danger btn-registration">Регистрация</button>
						
										<button type="button" class="btn btn-light btn-canel-registration">Отмена регистрации</button>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="row mt-2 event_cards">
				<div class="col-lg-12">
					<div class="card mb-3">
						<div class="row g-0">
							<div class="col-md-4">
								<img src="{% static "general/images/img.png" %}"
								class="img-fluid rounded-start" alt="...">
							</div>
							<div class="col-md-8">
								<div class="card-body">
									<h5 class="card-title">{{ 3_event_attended_title }}</h5>
									<h6 class="card-date"> 
										<split class="card-day"><b>01.03.2024</b></split> 
										<split class="card-time">14:00 - 18:00</split> </h6> 
									<p class="card-text">{{ 3_event_attended_info }}</p>
									<p class="card-text">
										<small class="text-muted">Тег</small>
									</p>
									<p class="card-text">
										<button type="button" class="btn btn-danger btn-registration">Регистрация</button>
						
										<button type="button" class="btn btn-light btn-canel-registration">Отмена регистрации</button>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-1"></div>
	</div>
</div>
{% endblock content %}

bookmarks/templates/bookmarks/send_message.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Отправка сообщения участникам</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
<div class="container mt-5">
    <h1>Отправка сообщения участникам</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.event_type.label_tag }}<br>
            {{ form.event_type }}
        </div>
        <div class="form-group">
            {{ form.event.label_tag }}<br>
            <select name="event" id="id_event" class="form-control">
                <option value="">---------</option>
                {% for event in form.event.field.queryset %}
                    <option value="{{ event.id }}">{{ event.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            {{ form.message.label_tag }}<br>
            {{ form.message }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить сообщение</button>
    </form>
</div>

<script>
    $(document).ready(function() {
        $('#id_event_type').change(function() {
            var eventType = $(this).val();
            $.ajax({
                url: "{% url 'bookmarks:get_event_choices' %}",
                data: {
                    'event_type': eventType
                },
                success: function(data) {
                    var eventSelect = $('#id_event');
                    eventSelect.empty();
                    eventSelect.append('<option value="">---------</option>');
                    $.each(data, function(index, event) {
                        eventSelect.append('<option value="' + event.id + '">' + event.name + '</option>');
                    });
                }
            });
        });
    });
</script>
</body>
</html>