SGUevents/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users.views import telegram_webhook

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('support/', include('support.urls', namespace='support')),
    path('events_available/', include('events_available.urls', namespace='events_available')),
    path('events_calendar/', include('events_calendar.urls', namespace='events_calendar')),
    path('events_cultural/', include('events_cultural.urls', namespace='events_cultural')),
    path('application_for_admin_rights/', include('application_for_admin_rights.urls', namespace='application_for_admin_rights')),
    path('personal/', include('personal.urls', namespace='personal')),
    path('select2/', include('django_select2.urls')),
    path('bookmarks/', include('bookmarks.urls', namespace='bookmarks')),
    path('webhook/', telegram_webhook, name='telegram_webhook'),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/urls.py
from django.urls import path
from bookmarks import views
from .views import send_message_to_participants, get_event_choices

app_name = 'bookmarks'

urlpatterns = [
    path('events_add/<slug:event_slug>/', views.events_add, name='events_add'),
    path('events_remove/<int:event_id>/', views.events_remove, name='events_remove'),
    path('favorites/', views.favorites, name='favorites'),

    path('favorites/', views.favorites, name='favorites'),
    path('favorites/<slug:event_slug>/', views.favorites, name='toggle_favorite'),

	path('events_attended/', views.events_attended, name='events_attended'),
	path('events_attended/<slug:event_slug>/', views.events_attended, name='events_attended'),

    path('events_registered/', views.events_registered, name='events_registered'),
    path('events_registered/<slug:event_slug>/', views.events_registered, name='events_registered'),
    path('registered_remove/<int:event_id>/', views.registered_remove, name='registered_remove'),
    path('registered/', views.registered, name='registered'),
    path('registered/<slug:event_slug>/', views.registered, name='registered'),
    path('send_message/', send_message_to_participants, name='send_message_to_participants'),
    path('get-event-choices/', get_event_choices, name='get_event_choices'),
    path('submit_review/<int:event_id>/', views.submit_review, name='submit_review'),
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
	path('search/all/', views.index, name='search_all')
]

users/urls.py
from django.urls import path
from .views import login_view, register, profile, logout, telegram_auth, change_password, request_admin_rights

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('telegram-auth/', telegram_auth, name='telegram_auth'),
    path('change-password/', change_password, name='change_password'),
    path('request-admin-rights/', request_admin_rights, name='request_admin_rights'),
]

users/models.py
import uuid
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.crypto import get_random_string
from transliterate import translit, exceptions


class Department(models.Model):
    department_id = models.CharField(max_length=50, unique=True, verbose_name='ID отдела')
    department_name = models.CharField(max_length=100, verbose_name='Название отдела')

    def __str__(self):
        return self.department_name

    class Meta:
        verbose_name = 'Отдел'
        verbose_name_plural = 'Отделы'

class CustomUserManager(BaseUserManager):
    def transliterate_username(self, last_name, first_name, middle_name=''):
        transliterated = ''
        try:
            transliterated = translit(last_name, 'ru', reversed=True)
            transliterated += translit(first_name[0], 'ru', reversed=True) if first_name else ''
            transliterated += translit(middle_name[0], 'ru', reversed=True) if middle_name else ''
        except exceptions.LanguageDetectionError:
            transliterated = last_name + (first_name[0] if first_name else '') + (middle_name[0] if middle_name else '')

        base_username = transliterated
        counter = 1
        while self.model.objects.filter(username=transliterated).exists():
            transliterated = f"{base_username}{counter}"
            counter += 1

        return transliterated

    def create_user(self, email=None, password=None, **extra_fields):
        if email:
            email = self.normalize_email(email)
        password = get_random_string(8) if password is None else password
        first_name = extra_fields.pop('first_name', '')
        last_name = extra_fields.pop('last_name', '')
        middle_name = extra_fields.pop('middle_name', '')
        department = extra_fields.pop('department', None)
        telegram_id = extra_fields.pop('telegram_id', None)

        username = extra_fields.pop('username', None) or self.transliterate_username(last_name, first_name, middle_name)

        user = self.model(
            email=email,
            username=username,
            first_name=first_name,
            last_name=last_name,
            middle_name=middle_name,
            department=department,
            telegram_id=telegram_id,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('first_name', 'Admin')
        extra_fields.setdefault('last_name', 'User')
        extra_fields.setdefault('department', Department.objects.get_or_create(department_id='1', defaults={'department_name': 'Administration'})[0])
        extra_fields.setdefault('telegram_id', 'default_telegram_id')

        if not email:
            raise ValueError('The Email must be set for superuser')
        if password is None:
            raise ValueError('Superuser must have a password')

        email = self.normalize_email(email)
        user = self.create_user(email, password, **extra_fields)

        user.save(using=self._db)
        return user

class User(AbstractUser):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    middle_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Отчество')
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, verbose_name='Отдел')
    telegram_id = models.CharField(max_length=100, unique=True, null=True, blank=True, verbose_name='Telegram ID')
    email = models.EmailField('email address', blank=True, null=True)

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.first_name} {self.middle_name} {self.last_name}".strip()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

class AdminRightRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Пользователь")
    reason = models.TextField(verbose_name="Основание")
    status = models.CharField(max_length=20, choices=[('pending', 'Ожидает'), ('granted', 'Предоставлено'), ('denied', 'Отказано')], default='pending', verbose_name="Статус")
    response = models.TextField(blank=True, null=True, verbose_name="Ответ")

    def __str__(self):
        return f"{self.user.username} - {self.status}"

    class Meta:
        verbose_name = "Запрос на админские права"
        verbose_name_plural = "Запросы на админские права"

class SupportRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    question = models.TextField(verbose_name="Вопрос")
    answer = models.TextField(verbose_name="Ответ", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_resolved = models.BooleanField(default=False, verbose_name="Решен")

    def __str__(self):
        return f"Запрос от {self.user.username} - {self.created_at}"

    class Meta:
        verbose_name = "Запрос в техподдержку"
        verbose_name_plural = "Запросы в техподдержку"

users/forms.py
from django import forms
from .models import User, Department

class RegistrationForm(forms.ModelForm):
    department_id = forms.CharField(
        max_length=50,
        required=True,
        label='ID отдела',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ID отдела'})
    )

    class Meta:
        model = User
        fields = ['last_name', 'first_name', 'middle_name', 'department_id', 'telegram_id']
        widgets = {
            'middle_name': forms.TextInput(attrs={'placeholder': 'Отчество (необязательно)', 'class': 'form-control'}),
            'telegram_id': forms.HiddenInput(),  # Скрытое поле для telegram_id
        }
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'middle_name': 'Отчество',
        }

    def clean_telegram_id(self):
        telegram_id = self.cleaned_data.get('telegram_id')
        if not telegram_id:
            raise forms.ValidationError("Требуется идентификатор Telegram для регистрации.")
        return telegram_id

    def clean_department_id(self):
        department_id = self.cleaned_data.get('department_id')
        if not Department.objects.filter(department_id=department_id).exists():
            raise forms.ValidationError("Отдел с указанным ID не найден.")
        return department_id

users/views.py
import json
import logging
import os
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.views.decorators.csrf import csrf_exempt

from .forms import RegistrationForm
from .models import Department, AdminRightRequest
from .telegram_utils import send_login_details_sync
from .telegram_utils import send_message_to_admin, send_confirmation_to_user
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from aiogram import types
from asgiref.sync import async_to_sync
from bot.main import handle_webhook

User = get_user_model()
logger = logging.getLogger(__name__)

DEV_BOT_NAME = os.getenv('DEV_BOT_NAME')

def home(request):
    return render(request, 'users/home.html')


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            generated_password = get_random_string(8)
            department_id = form.cleaned_data['department_id']
            department, _ = Department.objects.get_or_create(department_id=department_id)

            user_kwargs = {
                'email': form.cleaned_data.get('email'),
                'password': generated_password,
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'middle_name': form.cleaned_data.get('middle_name', ''),
                'department': department,
                'telegram_id': form.cleaned_data['telegram_id'],
            }
            new_user = User.objects.create_user(**user_kwargs)

            if new_user.telegram_id:
                send_login_details_sync(new_user.telegram_id, new_user.username, generated_password)

            return redirect('users:login')
    else:
        form = RegistrationForm()

    context = {
        'form': form,
        'telegram_bot_username': DEV_BOT_NAME if os.getenv('DJANGO_ENV') == 'development' else 'Event_sgu_bot',
    }
    return render(request, 'users/register.html', context)

def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            auth_login(request, user)
            request.session['login_method'] = 'Через логин и пароль'
            return redirect('main:index')
        else:
            messages.error(request, "Неверный логин или пароль.")
    context = {
        'telegram_bot_username': DEV_BOT_NAME if os.getenv('DJANGO_ENV') == 'development' else 'Event_sgu_bot'
    }
    return render(request, 'users/login.html', context)

@csrf_exempt
def telegram_auth(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        telegram_id = data.get('telegram_id')
        user = User.objects.filter(telegram_id=telegram_id).first()
        if user:
            auth_login(request, user)
            request.session['login_method'] = 'Через Telegram'
            return JsonResponse({'success': True, 'redirect_url': '/'})
        else:
            return JsonResponse({'success': False, 'error': 'User not registered. Please register.', 'redirect_url': '/users/register'})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request'})

@csrf_exempt
@login_required
def change_password(request):
    if request.method == 'POST' and request.user.telegram_id:
        new_password = get_random_string(8)
        request.user.set_password(new_password)
        request.user.save()
        send_login_details_sync(request.user.telegram_id, request.user.username, new_password)
        logger.info("Password changed, logging out user and redirecting to login page")
        logout(request)
        return redirect('/login/')
    else:
        logger.error("Failed to change password: Access denied or missing telegram_id")
        return JsonResponse({'success': False, 'error': 'Access denied.'})

@csrf_exempt
@login_required
def request_admin_rights(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            justification = data.get('reason', '')
            user_full_name = f"{request.user.last_name} {request.user.first_name} {' ' + request.user.middle_name if request.user.middle_name else ''}".strip()
            message = f"Запрос на админские права от {user_full_name}: {justification}"

            # Создание новой записи запроса на админские права
            new_request = AdminRightRequest(user=request.user, reason=justification)
            new_request.save()

            # Отправка сообщения администратору
            send_message_to_admin(request.user.telegram_id, message)
            # Уведомление пользователя о том, что запрос отправлен
            send_confirmation_to_user(request.user.telegram_id)

            return JsonResponse({'success': True,
                                 'message': 'Запрос на админские права отправлен администратору и зарегистрирован в системе.'})
        except json.JSONDecodeError:
            return JsonResponse({'success': False, 'error': 'Ошибка в формате данных.'})
    return JsonResponse({'success': False, 'error': 'Недопустимый запрос.'})

@login_required
def profile(request):
    user = request.user
    login_method = request.session.get('login_method', 'Неизвестный способ входа')
    department_name = user.department.department_name if user.department else 'Не указан'
    return render(request, 'users/profile.html', {'user': user, 'login_method': login_method, 'department_name': department_name})

@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:index'))

def general(request):
    return render(request, 'main/index.html')


@csrf_exempt
def telegram_webhook(request):
    if request.method == 'POST':
        return async_to_sync(handle_webhook)(request)  # Используем async_to_sync для вызова асинхронной функции
    return JsonResponse({"error": "Invalid request method"}, status=400)

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'users/css/users_sign_up.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
			<h1>Вход</h1>
			<p>Заполните форму/p>
		</div>
</body>
</html>

users/templates/users/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Главная страница</title>
    <!-- Подключение Bootstrap CSS для стилизации -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            flex-direction: column;
        }
        .btn {
            width: 200px; /* Ширина кнопок */
            margin: 10px; /* Отступы между кнопками */
        }
    </style>
</head>
<body>

<div class="container">
    <h1>Добро пожаловать!</h1>
    <a href="{% url 'users:login' %}" class="btn btn-success">Авторизация</a>
    <a href="{% url 'users:register' %}" class="btn btn-success">Регистрация</a>
    <a href="{% url 'main:index' %}" class="btn btn-secondary">Главная страница</a>
</div>

<!-- Включаем Bootstrap Bundle с Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

users/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Вход</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f8f9fa;
        }
        .container {
            background: white;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            width: 90%;
            max-width: 380px;
        }
        .btn-primary {
            background-color: #0088BB; /* Корпоративный цвет */
            border: none;
        }
        .btn-primary:hover {
            background-color: #0077A3; /* Немного темнее при наведении */
        }
        a {
            color: #0088BB; /* Ссылки в корпоративном цвете */
        }
        a:hover {
            color: #005577; /* Темнее при наведении */
        }
        .divider {
            display: flex;
            align-items: center;
            text-align: center;
            margin: 20px 0;
        }
        .divider::before,
        .divider::after {
            content: '';
            flex: 1;
            border-bottom: 1px solid #ccc;
        }
        .divider::before {
            margin-right: 10px;
        }
        .divider::after {
            margin-left: 10px;
        }
    </style>
</head>
<body>

<div class="container">
    <h2 class="mb-4 text-center">Вход</h2>

    <!-- Место для сообщений -->
    <div id="messageArea" class="alert alert-info" style="display: none;"></div>

    <form method="post" action="">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Логин</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Введите ваш логин">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Введите ваш пароль">
        </div>
        <button type="submit" class="btn btn-primary w-100">Войти</button>
    </form>

    <div class="divider">или</div>

    <div class="text-center">
        <p>Войдите через Telegram:</p>
        <script async src="https://telegram.org/js/telegram-widget.js?7" data-telegram-login="{{ telegram_bot_username }}" data-size="large" data-onauth="onTelegramAuth(user)" data-request-access="write"></script>
    </div>
    <div class="mt-3 text-center">
        Нет аккаунта? <a href="{% url 'users:register' %}">Регистрация</a>
    </div>
</div>

<script>
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '='))
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
        }
    }
    return cookieValue;
}

function onTelegramAuth(user) {
    console.log(user);
    fetch('/users/telegram-auth/', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': getCookie('csrftoken')
        },
        body: JSON.stringify({ telegram_id: user.id })
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            window.location.href = data.redirect_url;
        } else {
            alert(data.error);
        }
    });
}
</script>

</body>
</html>

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>Личный кабинет</title> {% endblock %}
{% block style %}
<style>
    body {
        background-color: #343a40;
        color: #f8f9fa;
    }
    .profile-card {
        background-color: #495057;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        max-width: 600px;
    }
    .profile-header {
        font-size: 1.3rem;
        margin-bottom: 15px;
    }
    .profile-detail {
        font-size: 1rem;
        margin-bottom: 10px;
    }
    .profile-detail strong {
        display: inline-block;
        width: 150px;
    }
    .btn-group {
        width: 100%;
        display: flex;
        justify-content: space-between;
        margin-top: 20px;
    }
</style>
{% endblock style %}
{% block content %}
<div class="container mt-3">
    <div class="row">
        <!-- Левый блок -->
        <div class='col-lg-7'>
            <div class="profile-card">
                <!-- Контент профиля -->
                <div class="profile-header text-center">
                    Профиль пользователя
                </div>
                <div class="profile-detail">
                    <strong>Имя пользователя:</strong> {{ user.username }}
                </div>
                <div class="profile-detail">
                    <strong>Отдел:</strong> {{ department_name }}
                </div>
                <div class="profile-detail">
                    <strong>Email:</strong> {{ user.email }}
                </div>
                <div class="profile-detail">
                    <strong>Telegram ID:</strong> {{ user.telegram_id }}
                </div>
                <div class="profile-detail">
                    <strong>Метод входа:</strong> {{ login_method }}
                </div>
                <div class="profile-detail">
                    <strong>Статус:</strong> <!-- Пока пустое поле -->
                </div>
                <div class="btn-group">
                    <button class="btn btn-warning" onclick="requestPasswordChange()">Сменить пароль</button>
                </div>
                <div class="mt-4">
                    <h2 class="h5">Запрос админских прав</h2>
                    <input type="text" id="reason" class="form-control" placeholder="Обоснование запроса">
                    <button class="btn btn-primary mt-2" onclick="requestAdminRights()">Отправить запрос</button>
                </div>
                <a href="/" class="btn btn-link mt-3">Вернуться на главную страницу</a>
            </div>
        </div>

        <!-- Правый блок -->
        <div class='col-lg-5'>
            <div class="profile-card">
                <!-- Дополнительная информация профиля -->
                <div class="profile-header text-center">
                    Права пользователя
                </div>
                <div class="profile-detail">
                    <strong>Роль </strong>
                    {% if user.is_superuser %}
                        Суперпользователь
                    {% elif user.is_staff %}
                        Администратор
                    {% else %}
                        Пользователь
                    {% endif %}
                </div>
                {% if user.is_superuser or user.is_staff %}
                    <div class="profile-detail">
                        <strong>Группы </strong>
                        {% for group in user.groups.all %}
                            {{ group.name }}
                        {% empty %}
                            Вы не состоите в группах
                        {% endfor %}
                    </div>
                {% endif %}


                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href={% url "bookmarks:send_message_to_participants" %}>Выслать уведомления участникам</a>
                </li>
            </div>
        </div>
    </div>
</div>

<script>
function requestPasswordChange() {
    fetch('{% url "users:change_password" %}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
        }
    })
    .then(response => response.json())
    .then(data => {
        alert(data.message);
    });
}

function requestAdminRights() {
    const reason = document.getElementById('reason').value;
    fetch('{% url "users:request_admin_rights" %}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
        },
        body: JSON.stringify({ reason: reason })
    })
    .then(response => response.json())
    .then(data => {
        alert(data.message);
        if (data.success) {
            document.getElementById('reason').value = ''; // Очистить поле ввода после успешной отправки
        }
    })
    .catch(error => {
        console.error('Ошибка:', error);
        alert('Произошла ошибка при отправке запроса на админские права.');
    });
}

</script>
{% endblock content %}

users/templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Регистрация</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f8f9fa;
        }
        .container {
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0,0,0,0.2);
            width: 100%;
            max-width: 400px;
        }
        .btn-primary {
            background-color: #0088BB; /* Корпоративный цвет */
            border: none;
        }
        .btn-primary:hover {
            background-color: #0077A3; /* Немного темнее при наведении */
        }
        a {
            color: #0088BB; /* Ссылки в корпоративном цвете */
        }
        a:hover {
            color: #005577; /* Темнее при наведении */
        }
        .alert-info {
            border-color: #0088BB;
            color: #005577;
            background-color: #e0f3ff;
        }
        .alert-success {
            background-color: #ccf2e8;
            border-color: #2ca8a0;
            color: #055D53;
        }
        .auth-status {
            margin-bottom: 15px;
            display: none; /* Скрыто по умолчанию */
        }
        .divider {
            display: flex;
            align-items: center;
            text-align: center;
            margin: 20px 0;
        }
        .divider::before,
        .divider::after {
            content: '';
            flex: 1;
            border-bottom: 1px solid #ccc; /* Светлее для более тонкого вида */
        }
        .divider::before {
            margin-right: 10px;
        }
        .divider::after {
            margin-left: 10px;
        }
    </style>
</head>
<body>

<div class="container">
    <h2 class="mb-4 text-center">Регистрация</h2>
    <div class="alert alert-info" role="alert">
        Для регистрации на портале введите ваше ФИО и код подразделения.
        <br>Код подразделения можно посмотреть на корпоративном портале.
        <br>Для регистрации необходимо авторизоватья через телеграм.
    </div>
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="errors">
            {% if form.errors %}
                <p>Пожалуйста, исправьте следующие ошибки:</p>
                {{ form.errors }}
            {% endif %}
        </div>
        <div class="text-center">
            <script async src="https://telegram.org/js/telegram-widget.js?7"
                    data-telegram-login="{{ telegram_bot_username }}" data-size="large"
                    data-onauth="onTelegramAuth(user)" data-request-access="write"></script>
        </div>
        <div id="authStatus" class="alert alert-success auth-status" style="display: none;">
            Вы успешно авторизовались через Telegram!
        </div>
        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary mt-3" id="signupButton" disabled>Зарегистрироваться</button>
        </div>
    </form>
</div>

<script>
    function onTelegramAuth(user) {
        console.log(user);
        document.getElementById('authStatus').style.display = 'block';
        document.getElementById('signupButton').disabled = false;
        document.getElementById('id_telegram_id').value = user.id;
    }
</script>

</body>
</html>

users/templates/users/result.html
<!DOCTYPE html>
<html>
<head>
    <title>Результат регистрации</title>
</head>
<body>
    <h1>Информация о регистрации:</h1>
    <p>ФИО пользователя: {{ full_name }}</p>
    <p>Код подразделения: {{ department_code }}</p>
</body>
</html>