SGUevents/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users.views import telegram_webhook

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('support/', include('support.urls', namespace='support')),
    path('events_available/', include('events_available.urls', namespace='events_available')),
    path('events_calendar/', include('events_calendar.urls', namespace='events_calendar')),
    path('events_cultural/', include('events_cultural.urls', namespace='events_cultural')),
    path('application_for_admin_rights/', include('application_for_admin_rights.urls', namespace='application_for_admin_rights')),
    path('personal/', include('personal.urls', namespace='personal')),
    path('select2/', include('django_select2.urls')),
    path('bookmarks/', include('bookmarks.urls', namespace='bookmarks')),
    path('webhook/', telegram_webhook, name='telegram_webhook'),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/urls.py
from django.urls import path
from bookmarks import views
from .views import send_message_to_participants, get_event_choices

app_name = 'bookmarks'

urlpatterns = [
    path('events_add/<slug:event_slug>/', views.events_add, name='events_add'),
    path('events_remove/<int:event_id>/', views.events_remove, name='events_remove'),
    path('favorites/', views.favorites, name='favorites'),

    path('favorites/', views.favorites, name='favorites'),
    path('favorites/<slug:event_slug>/', views.favorites, name='toggle_favorite'),

	path('events_attended/', views.events_attended, name='events_attended'),
	path('events_attended/<slug:event_slug>/', views.events_attended, name='events_attended'),

    path('events_registered/', views.events_registered, name='events_registered'),
    path('events_registered/<slug:event_slug>/', views.events_registered, name='events_registered'),
    path('registered_remove/<int:event_id>/', views.registered_remove, name='registered_remove'),
    path('registered/', views.registered, name='registered'),
    path('registered/<slug:event_slug>/', views.registered, name='registered'),
    path('send_message/', send_message_to_participants, name='send_message_to_participants'),
    path('get-event-choices/', get_event_choices, name='get_event_choices'),
    path('submit_review/<int:event_id>/', views.submit_review, name='submit_review'),
]

events_calendar/urls.py
from django.urls import path, include
from events_calendar import views

app_name = 'events_calendar'

urlpatterns = [
    path('', views.calendar_view, name='index'),
]

events_cultural/urls.py
from django.urls import path, include
from events_cultural import views

app_name = 'events_cultural'

urlpatterns = [
	path('attractions/search/', views.attractions, name='search_attractions'),
	path('events_for_visiting/search/', views.events_for_visiting, name='search_events_for_visiting'),


	path('attractions/<int:page>/', views.attractions, name='attractions'),
	path('attractions/', views.attractions, name='attractions'),
	path('attractions/<slug:event_slug>/', views.attractions_card, name='attractions_card'),

	# path('events_registered/', views.events_registered, name='events_registered'),
	# path('events_registered/<int:event_id>', views.events_registered_, name='events_registered_card'),
	# path('events_registered/event/<slug:event_slug>/', views.events_registered, name='events_registered_card'),

	path('events_for_visiting/<int:page>/', views.events_for_visiting, name='events_for_visiting'),
	path('events_for_visiting/', views.events_for_visiting, name='events_for_visiting'),
	path('events_for_visiting/<slug:event_slug>/', views.for_visiting_card, name='events_for_visiting_card'),

	path('submit_review/<int:event_id>/', views.submit_review, name='submit_review'),
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
	path('search/all/', views.index, name='search_all')
]

personal/urls.py
from django.urls import include, path
from . import views

app_name = 'personal'

urlpatterns = [
    path('', views.personal, name='personal'),
    # path('add_online_event/', views.add_online_event, name='add_online_event'),
    # path('add_offline_event/', views.add_offline_event, name='add_offline_event'),
	path('select2/', include('django_select2.urls')),
]

users/urls.py
from django.urls import path
from .views import login_view, register, profile, logout, telegram_auth, change_password, request_admin_rights

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('telegram-auth/', telegram_auth, name='telegram_auth'),
    path('change-password/', change_password, name='change_password'),
    path('request-admin-rights/', request_admin_rights, name='request_admin_rights'),
]

events_calendar/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from events_available.models import Events_online, Events_offline
from events_cultural.models import Attractions, Events_for_visiting
from bookmarks.models import Registered, Favorite
from django.urls import reverse
import json

@login_required
def calendar_view(request):
    events_online = Events_online.objects.all()
    events_offline = Events_offline.objects.all()
    attractions = Attractions.objects.all()
    events_for_visiting = Events_for_visiting.objects.all()
    
    registered_online_ids = Registered.objects.filter(user=request.user, online__isnull=False).values_list('online_id', flat=True)
    registered_offline_ids = Registered.objects.filter(user=request.user, offline__isnull=False).values_list('offline_id', flat=True)
    registered_attractions_ids = Registered.objects.filter(user=request.user, attractions__isnull=False).values_list('attractions_id', flat=True)
    registered_for_visiting_ids = Registered.objects.filter(user=request.user, for_visiting__isnull=False).values_list('for_visiting_id', flat=True)

    favorite_online_ids = Favorite.objects.filter(user=request.user, online__isnull=False).values_list('online_id', flat=True)
    favorite_offline_ids = Favorite.objects.filter(user=request.user, offline__isnull=False).values_list('offline_id', flat=True)
    favorite_attractions_ids = Favorite.objects.filter(user=request.user, attractions__isnull=False).values_list('attractions_id', flat=True)
    favorite_for_visiting_ids = Favorite.objects.filter(user=request.user, for_visiting__isnull=False).values_list('for_visiting_id', flat=True)
    
    events = []
    for event in events_online:
        event_data = {
            'title': f"{event.name}",
            'start': event.date.strftime("%Y-%m-%d"),
            'time': event.time_start.strftime("%H:%M"),
            'category': 'Онлайн',
            'css_class': 'event-online',  # Класс по умолчанию для онлайн событий
            'url': reverse('events_available:online_card', args=[event.slug])
        }
        if event.id in registered_online_ids:
            event_data['css_class'] += ' event-registered'  # Добавляем класс для зарегистрированных событий
        elif event.id in favorite_online_ids:
            event_data['css_class'] += ' event-favorite'  # Добавляем класс для избранных событий
        events.append(event_data)

    for event in events_offline:
        event_data = {
            'title': f"{event.name}",
            'start': event.date.strftime("%Y-%m-%d"),
            'time': event.time_start.strftime("%H:%M"),
            'category': 'Оффлайн',
            'css_class': 'event-offline',  # Класс по умолчанию для оффлайн событий
            'url': reverse('events_available:offline_card', args=[event.slug])
        }
        if event.id in registered_offline_ids:
            event_data['css_class'] += ' event-registered'
        elif event.id in favorite_offline_ids:
            event_data['css_class'] += ' event-favorite'
        events.append(event_data)

    for event in attractions:
        event_data = {
            'title': f"{event.name}",
            'start': event.date.strftime("%Y-%m-%d"),
            'time': event.time_start.strftime("%H:%M"),
            'category': 'Достопримечательность',
            'css_class': 'event-attractions',  # Класс по умолчанию для достопримечательностей
            'url': reverse('events_cultural:attractions_card', args=[event.slug])
        }
        if event.id in registered_attractions_ids:
            event_data['css_class'] += ' event-registered'
        elif event.id in favorite_attractions_ids:
            event_data['css_class'] += ' event-favorite'
        events.append(event_data)

    for event in events_for_visiting:
        event_data = {
            'title': f"{event.name}",
            'start': event.date.strftime("%Y-%m-%d"),
            'time': event.time_start.strftime("%H:%M"),
            'category': 'Для посещения',
            'css_class': 'event-visiting',  # Класс по умолчанию для событий для посещения
            'url': reverse('events_cultural:events_for_visiting_card', args=[event.slug])
        }
        if event.id in registered_for_visiting_ids:
            event_data['css_class'] += ' event-registered'
        elif event.id in favorite_for_visiting_ids:
            event_data['css_class'] += ' event-favorite'
        events.append(event_data)

    context = {
        'events': json.dumps(events)
    }
    return render(request, 'events_calendar/index.html', context)

events_calendar/templates/events_calendar/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'daterangepicker/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'general/css/general-page.css' %}">
    <link rel="stylesheet" href="{% static 'general/css/events_available.css' %}">
    <link rel="stylesheet" href="{% static 'calendar/css/calendar.css' %}">
    
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/locale/ru.js"></script> {% endcomment %}

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static "calendar/js/ru.js" %}"></script>

    <title>Календарь мероприятий</title>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark text-white">
            <div class="container-fluid">
                <a class="navbar-brand" href={% url "main:index" %}>Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'users:login' %}">Войти</a>
                        </li>
                        {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Доступные мероприятия
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href={% url "events_available:online" %}>Онлайн мероприятия</a></li>
                                <li><a class="dropdown-item" href={% url "events_available:offline" %}>Оффлайн мероприятия</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Культурные мероприятия
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href={% url "events_cultural:attractions" %}>Достопримечательности</a></li>
                                
                                <li><a class="dropdown-item" href={% url "events_cultural:events_for_visiting" %}>Доступные к посещению</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href={% url "events_calendar:index" %}>Календарь мероприятий</a>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Мой профиль </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item text-black" href="{% url 'users:profile' %}">Личный кабинет</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-black" href={% url "bookmarks:registered" %}>Зарегистрированные</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-black" href="{% url 'bookmarks:favorites' %}">Избранные</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-black" href="{% url 'bookmarks:events_attended' %}">Посещенные</a>
                                </li>
                                {% if user.is_admin or user.is_superuser %}
                                <li>
                                    <a class="dropdown-item text-black" href="{% url 'admin:index' %}">Админ панель</a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-black" href="{% url 'personal:personal' %}">Кабинет администратора</a>
                                </li>
                                {% endif %}
                                <li><hr class="dropdown-divider" /></li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
                                </li>
                            </ul>
                        </li>
                        
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" action="{% if name_page == 'Онлайн' %}{% url "events_available:search_online" %}{% elif name_page == 'Оффлайн' %}{% url "events_available:search_offline" %}{% elif name_page == 'Доступные к посещению' %}{% url "events_cultural:search_events_for_visiting" %}{% elif name_page == 'Достопримечательности' %}{% url "events_cultural:search_attractions" %}{% elif name_page == 'Все мероприятия' %}{% url "main:search_all" %}{% endif %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">
                            <img src="{% static "general/icons/search.svg" %}" alt="S">
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    </header>


<section class="container-fluid calendar-container">
    {% comment %} <h1 class="text-center my-4">Календарь мероприятий</h1> {% endcomment %}
    <div id="calendar"></div>
</section>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var events = {{ events|safe }};
        console.log(events);

        $('#calendar').fullCalendar({
            locale: 'ru',
            height: 'parent',
            events: events,
            eventRender: function(event, element) {
                element.css('background-color', event.backgroundColor); // Устанавливаем цвет события
                element.find('.fc-title').html('<a href="' + event.url + '" style="color:white;">' + event.title + '</a>');
                element.find('.fc-title').append('<br/><b>' + event.time + '</b><br/><i>' + event.category + '</i>');
            },
            dayRender: function(date, cell) {
                if (date.isSame(new Date(), "day")) {
                    cell.css("background-color", "yellow"); // Сегодняшняя дата выделена желтым
                }
            }
        });
    });
</script>
</body>
</html>